---
apiVersion: v1
kind: Service
metadata:
  name: colors
  labels:
    name: colors
  namespace: meshdemo
spec:
  ports:
  - port: 8080
  selector:
    app: colors
---
apiVersion: v1
kind: Service
metadata:
  name: colors-blue
  labels:
    name: colors-blue
  namespace: meshdemo
spec:
  ports:
  - port: 8080
  selector:
    name: colors-blue
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: colors-blue
  namespace: meshdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: colors-blue
        app: colors
    spec:
      serviceAccountName: xray-access
      containers:
      - name: colors-blue
        image: 072792469044.dkr.ecr.eu-west-1.amazonaws.com/meshdemo/colors:1.0.0
        ports:
        - containerPort: 8080
        args: ["--color", "blue"]
      - name: xray-daemon
        image: 072792469044.dkr.ecr.eu-west-1.amazonaws.com/temporary/aws-xray-daemon:0.5
        securityContext:
          runAsUser: 1337
        ports:
        - containerPort: 2000
          name: xray
          protocol: UDP
        env:
        - name: AWS_REGION
          value: eu-west-1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      - name: envoy
        env:
        - name: APPMESH_VIRTUAL_NODE_NAME
          value: mesh/meshdemo/virtualNode/colors-blue-meshdemo
        - name: ENVOY_LOG_LEVEL
          value: info
        - name: AWS_REGION
          value: eu-west-1
        - name: ENABLE_ENVOY_XRAY_TRACING
          value: "1"
        image: 840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.12.1.0-prod
        ports:
        - containerPort: 9901
          name: stats
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          runAsUser: 1337
      initContainers:
      - name: proxyinit
        env:
        - name: APPMESH_START_ENABLED
          value: "1"
        - name: APPMESH_IGNORE_UID
          value: "1337"
        - name: APPMESH_ENVOY_INGRESS_PORT
          value: "15000"
        - name: APPMESH_ENVOY_EGRESS_PORT
          value: "15001"
        - name: APPMESH_APP_PORTS
          value: 8080,2000
        - name: APPMESH_EGRESS_IGNORED_IP
          value: 169.254.169.254
        - name: APPMESH_EGRESS_IGNORED_PORTS
          value: "22"
        image: 111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:v2
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      serviceAccountName: xray-access
      securityContext:
        fsGroup: 65534
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: colors-blue
  namespace: meshdemo
spec:
  meshName: meshdemo
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: colors-blue.meshdemo.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: colors-green
  labels:
    name: colors-green
  namespace: meshdemo
spec:
  ports:
  - port: 8080
  selector:
    name: colors-green
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: colors-green
  namespace: meshdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: colors-green
        app: colors
    spec:
      serviceAccountName: xray-access
      containers:
      - name: colors-green
        image: 072792469044.dkr.ecr.eu-west-1.amazonaws.com/meshdemo/colors:1.0.0
        ports:
        - containerPort: 8080
        args: ["--color", "green"]
      - name: xray-daemon
        image: 072792469044.dkr.ecr.eu-west-1.amazonaws.com/temporary/aws-xray-daemon:0.5
        securityContext:
          runAsUser: 1337
        ports:
        - containerPort: 2000
          name: xray
          protocol: UDP
        env:
        - name: AWS_REGION
          value: eu-west-1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      - name: envoy
        env:
        - name: APPMESH_VIRTUAL_NODE_NAME
          value: mesh/meshdemo/virtualNode/colors-green-meshdemo
        - name: ENVOY_LOG_LEVEL
          value: info
        - name: AWS_REGION
          value: eu-west-1
        - name: ENABLE_ENVOY_XRAY_TRACING
          value: "1"
        image: 840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.12.1.0-prod
        ports:
        - containerPort: 9901
          name: stats
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          runAsUser: 1337
      initContainers:
      - name: proxyinit
        env:
        - name: APPMESH_START_ENABLED
          value: "1"
        - name: APPMESH_IGNORE_UID
          value: "1337"
        - name: APPMESH_ENVOY_INGRESS_PORT
          value: "15000"
        - name: APPMESH_ENVOY_EGRESS_PORT
          value: "15001"
        - name: APPMESH_APP_PORTS
          value: 8080,2000
        - name: APPMESH_EGRESS_IGNORED_IP
          value: 169.254.169.254
        - name: APPMESH_EGRESS_IGNORED_PORTS
          value: "22"
        image: 111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:v2
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      serviceAccountName: xray-access
      securityContext:
        fsGroup: 65534
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: colors-green
  namespace: meshdemo
spec:
  meshName: meshdemo
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  serviceDiscovery:
    dns:
      hostName: colors-green.meshdemo.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualService
metadata:
  name: colors
  namespace: meshdemo
spec:
  meshName: meshdemo
  virtualRouter:
    listeners:
      - portMapping:
          port: 8080
          protocol: http
  routes:
    - name: color-route
      http:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeName: colors-blue
              weight: 1
